### ISSUE TITLE
Not able to migrate app to nativescript 6 which supports only webPack work flow.

### ISSUE THREAD

**Issue by kranthi-kiki** [bradmartin/nativescript-cardview#114]
With NativeScript 6.0 the Webpack workflow will be the only way of building apps.
can you please provide when you are going to add Webpack feature.
We got stuck for this feature from migrating to Nativescript 6.0 . can you please update the plugin at the earliest.

![image](https://user-images.githubusercontent.com/46471488/64719744-8b87a500-d4e6-11e9-93cc-b1e58cd71770.png)

**Comment by bradmartin** [comment]
That's likely inaccurate. That must be looking for a key of some sort in the package.json.

The plugin source code can be webpacked as that is not the actual responsibility of the plugin source. Your app contains the webpack process where it will bundle the code. 
I don't really know why or what the purpose of that 'icon' is but there is nothing in the plugin source preventing someone from using it with webpack. That's the best info I have.

**Comment by bradmartin** [comment]
For reference, this plugin was shipped under the `@nstudio` scope with version NS6. The demo apps were updated https://github.com/nstudio/nativescript-cardview/blob/master/demo/package.json and they're on the webpack flow. So you can typically ignore those icons on the plugin marketplace. Maybe suggest to the NS team they change that or provide better context because that's odd to have the webpack icon disabled even though this works 🤷‍♂

**Comment by NathanaelA** [comment]
In addition the [ProPlugins](proplugins.org) version of the NativeScript-cardview has also been fully tested with NS6.
