### ISSUE TITLE
Cardview fails on IOS when running second time tns run command

### ISSUE THREAD

**Issue by nithinshiriya** [bradmartin/nativescript-cardview#22]
Cardview works fine on first tns run command. However when I re run the tns command then it fails.

**Comment by bradmartin** [comment]
Hi @nithinshiriya - I don't think the cardview plugin is the exact cause of this issue. This might be something better filed with NativeScript. If it works the first time, and then you are running it again (and nothing changed in the plugin) then it doesn't make sense to me that it's this plugin causing the problem. Hope that makes sense. If you create an issue with the NativeScript team please put the link here so I can follow along, I'm curious as to what your real problem is. Thanks 👍
