### ISSUE TITLE
iOS - Error when uploading App to iTunesConnect

### ISSUE THREAD

**Issue by lrsaturnino** [bradmartin/nativescript-cardview#30]
I'm trying to upload an App using Application Loader to iTunesConnect but I'm receiving the following error message:

![screen shot 2016-09-27 at 20 04 26](https://cloud.githubusercontent.com/assets/4065310/18895143/adcdc8b6-84ed-11e6-8cc3-46937bcd35d0.png)

Just to know, I built the App on AppBuilder from Telerik, downloaded the built App to upload it to iTunesConnect.

Any thoughts?

**Comment by bradmartin** [comment]
No experience with AppBuilder - this is all I could find from searching: http://stackoverflow.com/questions/37493049/itms-90668-invalid-bundle-executable-the-executable-file-contains-incomplete so it's something with the pods. Might need to update the pods used in the plugins if they are able to be upgraded. Have to check with some others to see how that works, I don't do much iOS work.

**Comment by NathanWalker** [comment]
@lrsaturnino when uploading with XCode Archive option... ensure you **uncheck** bitcode option. Not needed.

**Comment by bradmartin** [comment]
@lrsaturnino did @NathanWalker suggestion above help?

**Comment by bradmartin** [comment]
I'm going to close this, I just uploaded an app and was published to the app store without needing to modify the pod or anything underneath for iOS. I don't know much about the specifics but it can get through the Apple review system and builds. 

Hopefully you solved it since the last comment. If not feel free to let me or Nathan know so we can reopen.
