### ISSUE TITLE
Unable to build module

### ISSUE THREAD

**Issue by VladimirMilenko** [bradmartin/nativescript-cardview#39]
After cloning there is no way to build this package, also there is no style/Styler class in tns-core-modules which are installed with TNS.

**Comment by bradmartin** [comment]
If you clone and path to the demo you should be able to build and run just
fine. I tested a week ago on an app and all was normal. If you have
specific errors please post those. I'm also not following the styler
remark. Sorry. Again if you have any detailed errors post those for us.
Thanks

On Sun, Dec 25, 2016, 5:42 PM Vladimir Milenko <notifications@github.com>
wrote:

After cloning there is no way to build this package, also there is no
style/Styler class in tns-core-modules which are installed with TNS.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bradmartin/nativescript-cardview/issues/39>, or mute
the thread

**Comment by VladimirMilenko** [comment]
`cardview.android.ts(6,24): error TS2307: Cannot find module 'ui/styling/style'.
cardview.android.ts(14,21): error TS2503: Cannot find namespace 'android'.
cardview.android.ts(57,17): error TS2503: Cannot find namespace 'android'.
cardview.ios.ts(7,24): error TS2307: Cannot find module 'ui/styling/style'.
cardview.ios.ts(12,17): error TS2304: Cannot find name 'UIView'.`

Here is the error after running tsc.

**Comment by bradmartin** [comment]
So just typescript errors. You can bypass those a few ways. Simple approach
is the noEmitOnError flag in your tsconfig set to false

**Comment by bradmartin** [comment]
Hey @VladimirMilenko does that help any?

**Comment by bradmartin** [comment]
All is working now. Let me know if you still have issues. Running from the repo, you need to make sure you transpile the .ts to .executable .js files - you can check the scripts in the package.json for some info or just run `tsc` assuming you have typescript installed on your machine. Then path to demo app and execute `tns build ios` (or android) and it should work fine. I just fixed an issue with `app.ts` that caused a crash different than your original report. Hopefully you're good to go now 😄
