### ISSUE TITLE
NPM has old version

### ISSUE THREAD

**Issue by onury** [bradmartin/nativescript-cardview#42]
I see package.json has version 1.3.0
But on [NPM latest release](https://www.npmjs.com/package/nativescript-cardview) is 1.2.1

`tns plugin add nativescript-cardview` installs v 1.2.1

**Comment by bradmartin** [comment]
Repo isn't ready to publish just yet. I think we are waiting to fix up the
iOS version which removes the cocoa pod dependency.

On Wed, Jan 18, 2017, 9:26 AM Onur Yıldırım <notifications@github.com>
wrote:

I see package.json has version 1.3.0
But on NPM latest release
<https://www.npmjs.com/package/nativescript-cardview> is 1.2.1

tns plugin add nativescript-cardview installs v 1.2.1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bradmartin/nativescript-cardview/issues/42>, or mute
the thread

**Comment by onury** [comment]
Actually I get cocoapod error when I try to deploy to device (on simulator works fine).
That's the reason I wanted to see if I there is a newer version.

I get this error:
```
[Mounting] LookingUpImage
Successfully run application com.company.test on device with ID 1caa5fb8b2b94ebe814df1ae880dfcxxxxx.
dyld: Library not loaded: @rpath/MaterialCard.framework/MaterialCard
  Referenced from: /var/containers/Bundle/Application/BF711705-ED39-47AD-A8AA-CE24CF2AA958/test.app/test
  Reason: no suitable image found.  Did find:
	/private/var/contain
ers/Bundle/Application/BF711705-ED39-47AD-A8AA-CE24CF2AA958/test.app/Frameworks/MaterialCard.framework/MaterialCard: code signing blocked mmap() of '/private/var/containers/Bundle/Application/BF711705-ED39-47AD-A8AA-CE24CF2AA958/test.app/Frameworks/MaterialCard.framework/MaterialCard'
	/private/var/containers/Bundle/Application/BF711705-ED39-47AD-A8AA-CE24CF2AA958/test.app/Frameworks/MaterialCard.framework/MaterialCard: code signing blocked mmap() of '/private/var/containers/Bundle/Application/BF711705-ED39-47AD-A8AA-CE24CF2AA958/test.app/Frameworks/MaterialCard.framework/MaterialCard'
	/private/var/containers/Bundle/Application/BF711705-ED39-47AD-A8AA-CE24CF2AA958/test.app/Frameworks/MaterialCard.framework/MaterialCard: code signing blocked mmap() of '/private/var/containers/Bundle/Application/BF711705-ED39-47AD-A8AA-CE24CF2AA958/test.app/Frameworks/MaterialCard.framework/MaterialCard'
```
Mentioned [here](https://github.com/NathanWalker/MaterialCard/issues/2).

**Comment by bradmartin** [comment]
I'm awful at iOS specific stuff, not much help there. One thing I have seen a lot of with cocoapods is different versions will pull a pod fine and then a new pod version locally won't pull the cocoapod during a build. I think I stuck with version 0.39 because it was really stable and people upgrade to cocoapod 1.0 and had issues (not just nativescript devs using pods, but native iOS devs had same issues). It's a crap issue but I would check my pod version and then if you're on something other than 0.39, downgrade to it and then try rebuilding your app and running. Make sure you uninstall the old app from the simulator/device before running a new build to avoid any other conflicts there.

**Comment by bradmartin** [comment]
1.3.0 published

**Comment by onury** [comment]
Does this mean cocoa dep issue is fixed?

**Comment by bradmartin** [comment]
yep - there is no longer a pod dep 😄 

Make sure you follow the uninstall,build, run process to avoid conflicts. Outlined here if curious for more info https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/

**Comment by onury** [comment]
Tested, it works! Thanks Brad.
