### ISSUE TITLE
nativescript-cardview not found

### ISSUE THREAD

**Issue by demym** [bradmartin/nativescript-cardview#46]
Hi, i installed (npm install nativescript-cardview) cardview and included the xmlns in page (xmlns:Card="nativescript-cardview"), but my app crashes on the page containing it saying 'nativescript-cardview' not found.

I also tried to install cardview as a plugin (and installation was done, by the way). But same error.

tns 2.4.2,  vanilla nativescript (not angular2)

Any ideas ?
Thanks in advance

**Comment by bradmartin** [comment]
Run a new build after adding plugins. Also uninstall old builds from the
device so you are certain the new build is being ran. Normal native
development flow. Especially with Android devices

**Comment by elvismercado** [comment]
i am also having the same problem in the ios simulator: "could not find module nativescript-cardview".
this is right after cloning this git and running in demo folder.

**Comment by bradmartin** [comment]
@elvismercado - you likely missed the transpiling of the .ts source files into executable .js files before running the demo app which will pick up the source files in the root of this repo. I'm doing a clone test run right now. Will report back later. @demym - I'll also test the current published package on iOS and android to make sure things are good and report back.

**Comment by bradmartin** [comment]
Okay, fixed an issue with demo app.ts file. Must have been changed in a PR that went unnoticed, sorry. 

Also when you run locally, make sure to run `tsc` to transpile the .ts files because the repo doesn't host the .js - that's only on npm for the package. @elvismercado you have several routes to take to fix the app once you transpile (make sure you get the updated app.ts off the repo from the recent commit). Then delete the plugin folder `nativescript-cardview` out of the node_modules folder inside the `demo/app` path. Then when you `livesync` or `run` it will update the plugin in the `demo/app` node_modules with the transpiled .js and all should work.

**Comment by bradmartin** [comment]
I've gotten a test app to also work installing the plugin via `tns plugin add nativescript-cardview`. So you likely just need to back track and redo the install, build, and try from there. Hopefully you can get it going 😄

**Comment by elvismercado** [comment]
@bradmartin thanks for your work. I,ll try this ouy later
