### ISSUE TITLE
toggle shadow on card with clicks doesn't work on android

### ISSUE THREAD

**Issue by cindy-m** [bradmartin/nativescript-cardview#49]
I wanted to use the shadows to indicate what the user selected starting with no shadow and then showing the shadow when tapped one of the cards.
On iOS it works very good. Only on android it does not work that good. It always starts with a shadow and only works after the first click on it.
it seems as if the initial set value is not picked up by the android version.

**Comment by bradmartin** [comment]
Can you provide the code you're using to achieve this? If you have some visual that would help me the most 😄 I work faster that way

**Comment by cindy-m** [comment]
I use it like this:
<Card " [elevation]="selected ? '20' : '0'" [shadowOpacity]="selected ? '0.3' : '0'"
      shadowOffsetHeight="3" shadowRadius="2">

whereby at the start selected = false is and on tapping inside the card will set it to true.
Does this help?

**Comment by cindy-m** [comment]
tried out with a copy of the code and initialising the radius and elevation with 0 and removing the ifs in row 45 and 43 (if (this._elevation), if(this._radius)) does the trick and it works. I just don't know if this would be a wanted solution.

**Comment by bradmartin** [comment]
Hi @cindy-m - yea modifying the source isn't good if you ever update the modules or don't put modules on source control for a project (cause you'll lose them then 😄) If you're setting `elevation = 0` then `if(this._elevation)` evals to false because of 0. I'll add a check to make 0 be a possible setting here for `elevation` and `radius` thanks for testing that and confirming it works for your use case.

**Comment by bradmartin** [comment]
v1.3.2 on npm has the fix - let me know if you have any issues. thanks
