### ISSUE TITLE
radius doesn't work in ios

### ISSUE THREAD

**Issue by elimin8r** [bradmartin/nativescript-cardview#54]
I have tried various values of radius on ios and I can observe no difference in the appearance of the card. I am using {N} 3.

**Comment by danielgek** [comment]
@bradmartin and @elimin8r after investigation this(happen to me too), this only happens when you set backgroundColor through css or property in xml, i tried to fix it but it's out of my scope for now xD

**Comment by danielgek** [comment]
When we set back background color on a `<CardView backgroundColor="red" />`the color is appled to the `ContentView`  that has the `this.nativeView`, so the solution is whenever backgroundColor changes instead of setting the background color on the `ContentView` it should be `this.nativeView.backgroundColor` 

@bradmartin what do you think ?

**Comment by bradmartin** [comment]
Traveling for next week. When back I can review or try pinging one of the
other contributors. I haven't worked on this in a few months so my memory
is a little rusty on this one.

**Comment by danielgek** [comment]
@NathanWalker and @DickSmith what do you think?

**Comment by danielgek** [comment]
@bradmartin and @elimin8r  i gave it a go and summited a PR(#57) ;)
